[theme]

# Primary 
primaryColor = '#94cfff'

# Background color 
backgroundColor = '#041c36'

# Secondary Background color 
secondaryBackgroundColor= '#052547'

# Color for text
textColor = '#FFFFFF'

# Font family 
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"
font = "sans serif"
